version: "3.8"

services:
  nginx:
    image: socialscope-nginx-image:latest
    container_name: nginx_container
    networks:
      - socialscope_network
    depends_on:
      - socialscope
    ports: 
      - "80:80"

  socialscope:
    image: socialscope-image
    container_name: socialscope_container
    networks:
      - socialscope_network
    ports:
      - "3000:3000"

networks:
  socialscope_network:
